// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHelyM5AGsjX5niEn0ZhjQzahkOr60eEM',
    appId: '1:934067431026:web:8b2adf7859f8ce77e304eb',
    messagingSenderId: '934067431026',
    projectId: 'egypt-travel-app',
    authDomain: 'egypt-travel-app.firebaseapp.com',
    storageBucket: 'egypt-travel-app.appspot.com',
    measurementId: 'G-RJ6T1KTXF0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzgbRoFW-8xDScxYs729sbQ0wyJSwsYqE',
    appId: '1:934067431026:android:3aab5e7c6af660ade304eb',
    messagingSenderId: '934067431026',
    projectId: 'egypt-travel-app',
    storageBucket: 'egypt-travel-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmDT9Xw15masMAT86j-2zQrlndGIJaxl4',
    appId: '1:934067431026:ios:570f8486fc904f4fe304eb',
    messagingSenderId: '934067431026',
    projectId: 'egypt-travel-app',
    storageBucket: 'egypt-travel-app.appspot.com',
    iosClientId: '934067431026-60glsv5vlu7ff7t28p6mbgi9j198pe4e.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmDT9Xw15masMAT86j-2zQrlndGIJaxl4',
    appId: '1:934067431026:ios:570f8486fc904f4fe304eb',
    messagingSenderId: '934067431026',
    projectId: 'egypt-travel-app',
    storageBucket: 'egypt-travel-app.appspot.com',
    iosClientId: '934067431026-60glsv5vlu7ff7t28p6mbgi9j198pe4e.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelApp',
  );
}
